global class GlobalConstants {
    // Loa Sprint 8 Req#2787
    //Sunny test on 1226
    //Sunny test merge 2 and conflict and 1228
    //l Process 1507:
    Public Static String OPPORTUNITY = 'CloneOpportunity';
    Public Static String CLONE_OPPTY = 'getCloneOpp';
    //Approval Center component Req no: something 
    Public static String G4_G5='ted'; 
    Public static String G2 = 'G2';
    Public static String  G3= 'G3';
